services:
  # to validate the plugin
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'dlcmh/file-counter']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
